### ISSUE TITLE
Auto continuous/rolling/canary release for each PR land

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7555]
### Project

Deskflow

### Operating systems (OS)

- [X] Windows
- [X] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

n/a

### Deskflow configuration

n/a

### What problem are you trying to solve?

Testers shouldn't have to wait for a release to be manually published in order to test the latest changes.

### What solution do you propose?

Each time a PR lands, publish/update a release called continuous/rolling/canary which always shows at the top of the releases as the latest release. This way, the most available package is always the latest bleeding-edge code.

**Comment by marlop352** [comment]
currently the continuous tag only keeps the change notes from the last commit, shouldn't it list all changes since the last stable build?

**Comment by sithlord48** [comment]
Yeah you would like this but for some reason the auto notes generate only the diff from last continuous 
if you know how to fix that please lmk  ( but i do wonder if they list will become too long)

**Comment by marlop352** [comment]
> Yeah you would like this but for some reason the auto notes generate only the diff from last continuous if you know how to fix that please lmk ( but i do wonder if they list will become too long)

I never used github actions/workflow before so I'm not of much help there.
The only thing I can say is that looking at how https://github.com/LizardByte/Sunshine do their test releases may help as their pre-releases have a list of all changes since the last stable release.
Their method may require the continuous release to be marked as pre-release though but I'm not sure.

The list will become a tad long but I don't think that is a problem, well, at least not in the way Sunshine does them.
