### ISSUE TITLE
Installers for older versions

### ISSUE THREAD

**Issue by DavidBevi** [deskflow/deskflow#7628]
### Issue

Where can I download old versions of Deskflow, so that I can use it on an old machine?
Releases do not contain installers, is it a conscious decision to exclude every user that has no clue on how to compile an app like me?

### Proposed solution

Keep exe/msi/dmg files in the releases

**Comment by nbolton** [comment]
We [included the binaries with 1.17.0](https://github.com/deskflow/deskflow/releases) for the first time since rebranding from Synergy 1 Community Edition to Deskflow.

Deskflow's philosophy is leading edge, so we do not intend to go back in time and build binaries for older versions (when it was Synergy) as this would detract from forward momentum. If you need an older version, your only option would be to use Synergy. There are older versions (around v1.8) of Synergy that do not require a serial key and are mirrored. One example is: https://sourceforge.net/projects/synergy-stable-builds/files/v1.8.8-stable/
