### ISSUE TITLE
Move warnings as errors to CMake presets

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7726]
### Project

Deskflow

### What problem are you trying to solve?

Inconsistencies between CI and local dev env waste time. For example, I lost time today because warnings as errors were only in CI and not in the local dev env setup. I know that this can be set manually in my dev env, but because I develop across a lot of machines, I need a consistent development environment across all of them. Manually tweaking CMake settings and keeping everything in sync is counterproductive. Contributors will face this problem too.

### What solution do you propose?

We need to stop putting CMake `-D` options only in CI and move them to the CMake presets.

**Comment by sithlord48** [comment]
The fact that you would even suggest all options for cmake need to go in a preset should how little you understand cmake.
we don't want all options in preset because then instead of the user setting a var that is know like CMAKE_WARNINGS_AS_ERRORS we get to now dig thru a preset file to find a preset with the settings we want.. and if you don't find one now you have to make it.. 

Presets are useful to set generic options.NOT to set all the options

**Comment by nbolton** [comment]
I understand the concern, but I think there's a middle ground here. Presets aren't meant to replace every individual setting a developer might need, but they can provide a standardized starting point. Having common configurations in a preset can save time and ensure consistency, especially in environments like CI.

Regarding CMAKE_WARNINGS_AS_ERRORS, developers can still override or append options as needed for their specific case (that's what `CMakeUserPresets.json` is for). The idea is to streamline the setup for the majority, while still giving flexibility to those who need it.

It’s not about forcing all options into presets but rather providing a solid base that can be customized.

**Comment by sithlord48** [comment]
we do not want it as a default. we only do it ONLY on the ci so its set on the ci configure line. so its clear to those reading the job scrpt that it has been set.

**Comment by nbolton** [comment]
> but you are as `-D` is what sets options in cmake.

I'm referring to CI, specifically. Set whatever `-D` you like on your local env.

My main concern is creating an easy way to mirror CI, which is to use the _optional_ cmake presets.

It must be possible to develop without using the cmake presets. I am definitely not suggesting that people have to use it. It's a convenience for people who want to stay consistent with CI env.

**Comment by nbolton** [comment]
> the presets will be auto loaded by most IDE so you are forcing them on all.

Not true. In most IDEs you have to specifically choose a preset, and the IDE will let you proceed with unspecified. If the developer doesn't like the preset, they can choose not to use it, override with `-D` or use `CMakeUserPresets.json`.

**Comment by sithlord48** [comment]
They will all by default use the preset and the user has to do extra stuff to opt out.

**Comment by sithlord48** [comment]
I think my objection here boils down to this 

It is simply not our place to set any of these for the user, The more you hide settings and options in scrips, presets the more you hide them from the person building the project. And yes this sure helps get newer uses set up but I also hinders them later if they have to change the config or have issues as they have no idea about the configuration of their build setup .

**Comment by gabeklavans** [comment]
I agree that CMakePresets are certainly designed to be an optional step. And while it may be true that VSCode may choose a preset by default if you configure the project through the cmake extension (how does it choose the default, by the way? is it just the first one listed?) then I consider that something for the developer to figure out. Similar to the fact that if the developer is unwilling to learn about how to configure cmake for their system to disable warnings as errors (which by the way, I would love to see an example of a specific system configuration throwing a warning as error. I'm not experienced with this outcome), then that may be a sign of other problems for the dev.

However, I think that's all an aside. Instead of discussing ambiguously about adding things to the presets, let's just make PRs for changing the presets and we can discuss the specifics there. Unless @sithlord48 are you against presets entirely?

**Comment by nbolton** [comment]
I had a quick call with @sithlord48 today to get on the same page, and I've come around to his perspective. I started a wiki page to document our philosophy to make sure we're all on the same page: [Project Config](https://github.com/deskflow/deskflow/wiki/Project-Config)

Replying to @gabeklavans:

> how does it choose the default, by the way? is it just the first one listed?

With the CMake extension installed, it asks you to pick a preset... so I can see how this might come across as non-optional. Seems like extensions and IDEs make it a bit fiddly to not choose a preset if there are presets. Therefore, path of least resistance means people are most likely to choose a preset.

We also explored Qt Creator, which has a similar issue. It is possible to skip the preset but the easiest route is to pick one and accept whatever "hidden" values it chooses for you.

> then I consider that something for the developer to figure out. 

I think this is @sithlord48's point, too. It's better for the dev to figure it out rather than hiding stuff from them. Not because it's a right of passage or whatever, but because if they have to do the steps then they'll understand better how stuff works.

> then that may be a sign of other problems for the dev.

This is also true. If a dev won't take the time to learn the build env, what kind of value will they really add? I think @sithlord48 made this point when we were on a call at the weekend, IIRC.

> However, I think that's all an aside. Instead of discussing ambiguously about adding things to the presets, let's just make PRs for changing the presets and we can discuss the specifics there. 

I wanted to get a high level discussion going about the CMake presets... warnings as errors was just what sparked it. Incidentally I'm going to close out my PR and document an alternative approach which works better with our philosophy (if it works).

> Unless @sithlord48 are you against presets entirely?

Yes, he believes it's overkill for a project because the downsides (forcing new contribs to do things a certain way in their env) outweigh the upsides (saving time for some devs).

I liked this quote:
> "The more we try to force things, the more you're gimping your project." -- Chris (@sithlord48)
